# Generated by Django 3.1 on 2020-08-27 06:29

from django.db import migrations, models
import mirage.fields
import server.corelib.sequence.instaflake


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SmsRecord',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='更新时间')),
                ('extra', models.JSONField(default=dict, verbose_name='扩展数据')),
                ('bid', models.BigIntegerField(default=server.corelib.sequence.instaflake.bid_generator, primary_key=True, serialize=False)),
                ('scene', models.CharField(choices=[('code', '短信验证码'), ('msgr-s-10', '需要挪车'), ('msgr-s-12', '发生剐蹭'), ('msgr-s-20', '车窗没关'), ('msgr-s-99', '留言提醒'), ('invite', '邀请注册')], max_length=25, verbose_name='场景')),
                ('number', mirage.fields.EncryptedCharField(db_index=True, max_length=50, verbose_name='手机号')),
                ('usrid', models.BigIntegerField(db_index=True, default=0, verbose_name='触发用户')),
                ('touchid', models.BigIntegerField(db_index=True, default=0, verbose_name='触达用户')),
                ('bizid', models.CharField(db_index=True, default='', max_length=50, verbose_name='回执')),
                ('sign', models.CharField(default='', max_length=25, verbose_name='签名')),
                ('template', models.CharField(default='', max_length=50, verbose_name='模板')),
                ('params', models.JSONField(default=dict, verbose_name='模板参数')),
                ('status', models.SmallIntegerField(choices=[(0, '待发送'), (1, '等待回执'), (2, '发送失败'), (3, '发送成功')], default=0, verbose_name='发送状态')),
                ('report_at', models.DateTimeField(default=None, null=True, verbose_name='收到运营商回执时间')),
                ('send_at', models.DateTimeField(default=None, null=True, verbose_name='转发给运营商时间')),
                ('instid', models.BigIntegerField(db_index=True, default=0, verbose_name='关联对象')),
                ('err_msg', models.CharField(default='', max_length=200, verbose_name='错误信息')),
                ('err_code', models.CharField(default='', max_length=50, verbose_name='错误码')),
            ],
            options={
                'verbose_name': 'SmsRecord',
                'verbose_name_plural': 'SmsRecord',
                'db_table': 'k_os_sms_record',
                'ordering': ('-created_at',),
                'index_together': {('scene', 'status', 'err_code')},
            },
        ),
        migrations.CreateModel(
            name='ImageScan',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='更新时间')),
                ('extra', models.JSONField(default=dict, verbose_name='扩展数据')),
                ('bid', models.BigIntegerField(default=server.corelib.sequence.instaflake.bid_generator, primary_key=True, serialize=False)),
                ('oss_key', models.URLField(default='', verbose_name='图片路径')),
                ('usrid', models.BigIntegerField(db_index=True, default=0, verbose_name='用户')),
                ('mode', models.PositiveSmallIntegerField(choices=[(0, '初始化'), (5, '二维码'), (8, 'OCR车牌号'), (999, '无法识别')], default=0, verbose_name='模式')),
                ('convid', models.UUIDField(db_index=True, default=None, null=True, verbose_name='会话')),
                ('reason', models.CharField(default='', max_length=200, verbose_name='原因')),
                ('use_ms', models.PositiveSmallIntegerField(default=0, verbose_name='耗时')),
                ('is_valid', models.BooleanField(default=False, verbose_name='是否有效')),
                ('location', models.JSONField(default=dict, verbose_name='位置信息')),
                ('result', models.JSONField(default=dict, verbose_name='结果')),
            ],
            options={
                'verbose_name': 'ImageScan',
                'verbose_name_plural': 'ImageScan',
                'db_table': 'k_os_image_scan',
                'ordering': ('-pk',),
                'index_together': {('mode', 'is_valid')},
            },
        ),
        migrations.CreateModel(
            name='ImageOcr',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='更新时间')),
                ('extra', models.JSONField(default=dict, verbose_name='扩展数据')),
                ('bid', models.BigIntegerField(default=server.corelib.sequence.instaflake.bid_generator, primary_key=True, serialize=False)),
                ('oss_key', models.URLField(unique=True, verbose_name='图片路径')),
                ('usrid', models.BigIntegerField(db_index=True, default=0, verbose_name='用户')),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='置信度')),
                ('ocr_type', models.PositiveSmallIntegerField(choices=[(2, '二维码'), (5, '车牌'), (11, '身份证正面'), (12, '身份证反面'), (22, '驾驶证'), (33, '行驶证')], default=0, verbose_name='OCR类型')),
                ('suggestion', models.CharField(choices=[('pass', '正常'), ('review', '不确定'), ('block', '违规')], default='', max_length=20, verbose_name='建议操作')),
                ('ocr_use_ms', models.PositiveSmallIntegerField(default=0, verbose_name='OCR耗时')),
                ('reason', models.CharField(default='', max_length=200, verbose_name='原因')),
                ('is_victor', models.BooleanField(default=None, null=True, verbose_name='是否成功')),
                ('result', models.JSONField(default=dict, verbose_name='结果')),
            ],
            options={
                'verbose_name': 'ImageOcr',
                'verbose_name_plural': 'ImageOcr',
                'db_table': 'k_os_image_ocr',
                'ordering': ('-pk',),
                'index_together': {('ocr_type', 'suggestion', 'is_victor')},
            },
        ),
        migrations.CreateModel(
            name='CallRecord',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='更新时间')),
                ('extra', models.JSONField(default=dict, verbose_name='扩展数据')),
                ('bid', models.BigIntegerField(default=server.corelib.sequence.instaflake.bid_generator, primary_key=True, serialize=False)),
                ('msgid', models.BigIntegerField(unique=True, verbose_name='消息')),
                ('usrid', models.BigIntegerField(db_index=True, default=0, verbose_name='主叫用户')),
                ('touchid', models.BigIntegerField(db_index=True, default=0, verbose_name='被叫用户')),
                ('req_id', models.CharField(default=None, max_length=50, null=True, unique=True, verbose_name='呼叫ID(供应商)')),
                ('status', models.SmallIntegerField(choices=[(210, '正在呼叫'), (220, '正在转接'), (300, '正在通话'), (410, '呼叫取消'), (420, '暂未接通'), (500, '通话结束')], default=0, verbose_name='呼叫状态')),
                ('caller', mirage.fields.EncryptedCharField(default='', max_length=50, verbose_name='主叫号码')),
                ('called', mirage.fields.EncryptedCharField(default='', max_length=50, verbose_name='被叫号码')),
                ('callers_at', models.DateTimeField(db_index=True, default=None, null=True, verbose_name='主叫接听时间')),
                ('callere_at', models.DateTimeField(db_index=True, default=None, null=True, verbose_name='主叫挂机时间')),
                ('calleds_at', models.DateTimeField(db_index=True, default=None, null=True, verbose_name='被叫接听时间')),
                ('callede_at', models.DateTimeField(db_index=True, default=None, null=True, verbose_name='被叫挂机时间')),
                ('status_at', models.DateTimeField(default=None, null=True, verbose_name='状态同步时间戳')),
                ('duration', models.PositiveSmallIntegerField(default=0, verbose_name='通话时长(秒)')),
                ('call_state', models.CharField(default='', max_length=20, verbose_name='结果状态')),
                ('provider', models.CharField(default='', max_length=20, verbose_name='服务提供商')),
                ('cost', models.PositiveSmallIntegerField(default=0, verbose_name='成本')),
                ('fee', models.PositiveSmallIntegerField(default=0, verbose_name='计费')),
                ('is_record', models.BooleanField(default=False, verbose_name='是否录音')),
                ('record_file', models.URLField(default='', verbose_name='录音文件')),
            ],
            options={
                'verbose_name': 'CallRecord',
                'verbose_name_plural': 'CallRecord',
                'db_table': 'k_os_call_record',
                'ordering': ('-created_at',),
                'index_together': {('provider', 'status', 'call_state')},
            },
        ),
    ]
