# Generated by Django 3.1.2 on 2020-11-02 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outside', '0002_auto_20200915_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsrecord',
            name='scene',
            field=models.CharField(choices=[('msg-unread', '消息未读提醒'), ('msg-missed', '来电未接提醒')], max_length=25, verbose_name='场景'),
        ),
    ]
