# Generated by Django 3.1.2 on 2020-11-02 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outside', '0003_auto_20201102_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callrecord',
            name='status',
            field=models.SmallIntegerField(choices=[(0, '-'), (210, '正在呼叫'), (220, '正在转接'), (300, '正在通话'), (410, '呼叫取消'), (420, '暂未接通'), (500, '通话结束')], default=0, verbose_name='呼叫状态'),
        ),
    ]
