# Generated by Django 3.1.3 on 2020-11-03 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outside', '0004_auto_20201103_0020'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='更新时间')),
                ('extra', models.JSONField(default=dict, verbose_name='扩展数据')),
                ('cate', models.CharField(choices=[('uc-off', '用户码及通话关闭')], max_length=20, verbose_name='类型')),
                ('key', models.CharField(blank=True, db_index=True, default='', max_length=50, verbose_name='Key')),
                ('value', models.CharField(blank=True, default='', max_length=200, verbose_name='Value')),
                ('sort', models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='排序权重')),
                ('memo', models.CharField(blank=True, default='', max_length=100, verbose_name='备忘')),
                ('begin_at', models.DateTimeField(db_index=True, verbose_name='生效时间')),
                ('finish_at', models.DateTimeField(db_index=True, verbose_name='失效时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
            ],
            options={
                'verbose_name': 'Configuration',
                'verbose_name_plural': 'Configuration',
                'db_table': 'k_os_configuration',
                'unique_together': {('cate', 'key', 'sort')},
                'index_together': {('cate', 'sort', 'is_active')},
            },
        ),
    ]
