# Generated by Django 3.1 on 2020-08-27 06:29

import django.contrib.postgres.fields.ranges
from django.db import migrations, models
import mirage.fields
import server.constant.validator
import server.corelib.sequence.instaflake


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='更新时间')),
                ('extra', models.JSONField(default=dict, verbose_name='扩展数据')),
                ('model', models.CharField(max_length=200, unique=True, verbose_name='型号')),
                ('vehicle_type', models.CharField(default='', max_length=100, verbose_name='类型')),
                ('brand', models.CharField(default='', max_length=100, verbose_name='品牌')),
                ('series', models.CharField(default='', max_length=100, verbose_name='系列')),
                ('prices', django.contrib.postgres.fields.ranges.IntegerRangeField(default=(None, None), verbose_name='价格区间(万)')),
                ('count', models.PositiveIntegerField(default=0, verbose_name='数量')),
            ],
            options={
                'verbose_name': 'VehicleModel',
                'verbose_name_plural': 'VehicleModel',
                'db_table': 'k_ls_vehicle_model',
                'ordering': ('-pk',),
                'index_together': {('vehicle_type', 'brand', 'series')},
            },
        ),
        migrations.CreateModel(
            name='VehicleLicense',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='更新时间')),
                ('extra', models.JSONField(default=dict, verbose_name='扩展数据')),
                ('bid', models.BigIntegerField(default=server.corelib.sequence.instaflake.bid_generator, primary_key=True, serialize=False)),
                ('oss_key', models.URLField(db_index=True, default='', verbose_name='图片路径')),
                ('usrid', models.BigIntegerField(db_index=True, default=0, verbose_name='用户')),
                ('plate_num', models.CharField(db_index=True, default='', max_length=20, verbose_name='车牌号')),
                ('vehicle_type', models.CharField(default='', max_length=100, verbose_name='车辆类型')),
                ('use_character', models.CharField(default='', max_length=100, verbose_name='车辆使用性质')),
                ('owner', mirage.fields.EncryptedCharField(default='', max_length=200, verbose_name='所有者名字')),
                ('address', mirage.fields.EncryptedCharField(default='', max_length=255, verbose_name='住址')),
                ('vin', mirage.fields.EncryptedCharField(default='', max_length=100, verbose_name='车辆识别代号')),
                ('engine_num', mirage.fields.EncryptedCharField(default='', max_length=100, verbose_name='发动机号码')),
                ('model', models.CharField(default='', max_length=200, verbose_name='车辆品牌')),
                ('register_date', models.DateField(default=None, null=True, verbose_name='注册日期')),
                ('issue_date', models.DateField(default=None, null=True, verbose_name='发证日期')),
                ('reason', models.CharField(default='', max_length=200, verbose_name='原因')),
                ('verified_at', models.DateTimeField(default=None, null=True, verbose_name='验证时间')),
                ('is_verified', models.BooleanField(default=False, verbose_name='已验证')),
            ],
            options={
                'verbose_name': 'VehicleLicense',
                'verbose_name_plural': 'VehicleLicense',
                'db_table': 'k_ls_vehicle_license',
                'ordering': ('-pk',),
                'index_together': {('vehicle_type', 'use_character', 'model', 'is_verified')},
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='更新时间')),
                ('extra', models.JSONField(default=dict, verbose_name='扩展数据')),
                ('bid', models.BigIntegerField(default=server.corelib.sequence.instaflake.bid_generator, primary_key=True, serialize=False)),
                ('usrid', models.BigIntegerField(db_index=True, default=0, verbose_name='用户')),
                ('shahash', models.CharField(max_length=50, unique=True, verbose_name='SHA1签名')),
                ('vehicle_num', models.CharField(db_index=True, max_length=20, verbose_name='车牌号')),
                ('vehicle_type', models.PositiveSmallIntegerField(choices=[(11, '小型汽车'), (22, '新能源车'), (32, '大型汽车'), (35, '挂车'), (50, '教练车'), (62, '警车'), (65, '军车'), (72, '使领馆车'), (75, '港澳车')], verbose_name='车牌类型')),
                ('symbol', models.CharField(default=None, max_length=10, null=True, unique=True, verbose_name='场景码')),
                ('relation', models.PositiveSmallIntegerField(choices=[(0, '其他'), (10, '自己'), (20, '家属'), (30, '亲友'), (40, '同事')], default=0, verbose_name='所有者关系')),
                ('model_id', models.PositiveIntegerField(db_index=True, default=0, verbose_name='车辆型号')),
                ('license_id', models.BigIntegerField(db_index=True, default=0, verbose_name='行驶证ID')),
            ],
            options={
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'Vehicle',
                'db_table': 'k_ls_vehicle',
                'ordering': ('-pk',),
                'unique_together': {('vehicle_num', 'vehicle_type')},
                'index_together': {('vehicle_type', 'relation')},
            },
        ),
        migrations.CreateModel(
            name='Symbol',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='更新时间')),
                ('extra', models.JSONField(default=dict, verbose_name='扩展数据')),
                ('bid', models.BigIntegerField(default=server.corelib.sequence.instaflake.bid_generator, primary_key=True, serialize=False)),
                ('symbol', models.CharField(default=None, help_text='只能为10位纯字母', max_length=10, null=True, unique=True, validators=[server.constant.validator.SymbolValidator()], verbose_name='场景码')),
                ('usrid', models.BigIntegerField(db_index=True, default=0, verbose_name='用户')),
                ('phoneid', models.BigIntegerField(db_index=True, default=0, verbose_name='手机号ID')),
                ('scene', models.PositiveSmallIntegerField(choices=[(0, '场景码'), (11, '挪车码'), (22, '行李贴'), (33, '宠物牌')], default=0, verbose_name='场景')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, '初始化'), (10, '已发行'), (20, '已绑定'), (24, '已关闭'), (40, '已删除'), (44, '已作废')], default=0, verbose_name='状态')),
                ('meet', models.CharField(default='', max_length=255, verbose_name='自动回复')),
                ('title', models.CharField(default='', max_length=200, verbose_name='别名')),
                ('summary', models.CharField(default='', max_length=200, verbose_name='摘要')),
                ('ocropen', models.BooleanField(default=True, verbose_name='允许OCR识别')),
                ('ct_trigger', models.PositiveIntegerField(default=0, verbose_name='触发量')),
                ('ct_call', models.PositiveIntegerField(default=0, verbose_name='有效通话次数')),
                ('bound_at', models.DateTimeField(db_index=True, default=None, null=True, verbose_name='绑定时间')),
                ('limit_at', models.DateTimeField(db_index=True, default=None, null=True, verbose_name='限定激活时间')),
                ('selfdom', models.CharField(default='', max_length=20, verbose_name='自定义签名')),
                ('version', models.PositiveSmallIntegerField(default=1, verbose_name='版本')),
                ('is_pre', models.BooleanField(default=False, verbose_name='预发布')),
            ],
            options={
                'verbose_name': 'Symbol',
                'verbose_name_plural': 'Symbol',
                'db_table': 'k_ls_symbol',
                'ordering': ('-pk',),
                'index_together': {('scene', 'status', 'version', 'is_pre')},
            },
        ),
    ]
