# Generated by Django 3.1.1 on 2020-09-10 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('release', '0002_auto_20200910_1853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='symbol',
            name='phoneid',
        ),
    ]
