# Generated by Django 3.1.1 on 2020-09-19 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('release', '0003_remove_symbol_phoneid'),
    ]

    operations = [
        migrations.AddField(
            model_name='symbol',
            name='pages',
            field=models.PositiveIntegerField(default=0, verbose_name='页面量'),
        ),
        migrations.AddField(
            model_name='symbol',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='查询量'),
        ),
        migrations.AlterField(
            model_name='symbol',
            name='selfdom',
            field=models.CharField(default='', max_length=200, verbose_name='自定义签名'),
        ),
    ]
