# Generated by Django 3.1.2 on 2020-10-25 15:59

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import server.constant.validator
import server.third.aliyun.oss.oss_path


class Migration(migrations.Migration):

    dependencies = [
        ('release', '0005_remove_symbol_meet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='symbol',
            name='summary',
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='更新时间')),
                ('extra', models.JSONField(default=dict, verbose_name='扩展数据')),
                ('name', models.CharField(default=None, max_length=100, null=True, unique=True, verbose_name='名字')),
                ('scene', models.PositiveSmallIntegerField(choices=[(0, '场景码'), (11, '挪车码'), (22, '行李贴'), (33, '宠物牌')], default=0, verbose_name='场景')),
                ('sample', models.ImageField(blank=True, default=None, null=True, upload_to=server.third.aliyun.oss.oss_path.subject_sample, verbose_name='样品')),
                ('material', models.ImageField(blank=True, default=None, null=True, upload_to=server.third.aliyun.oss.oss_path.subject_material, verbose_name='素材')),
                ('coords', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, help_text='素材二维码放置坐标：x1, y1, x2, y2', size=4, verbose_name='坐标')),
                ('summary', models.CharField(blank=True, default='', max_length=200, verbose_name='摘要')),
                ('designer', models.CharField(blank=True, default='', max_length=100, verbose_name='设计师')),
                ('batch', models.PositiveSmallIntegerField(default=0, verbose_name='发行批次')),
                ('activated', models.PositiveIntegerField(default=0, verbose_name='已激活')),
                ('total', models.PositiveIntegerField(default=0, verbose_name='发行总量')),
                ('record', models.JSONField(default=dict, verbose_name='发行记录')),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subject',
                'db_table': 'k_ls_subject',
                'ordering': ('-pk',),
                'index_together': {('scene', 'designer')},
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='更新时间')),
                ('extra', models.JSONField(default=dict, verbose_name='扩展数据')),
                ('symbol', models.CharField(help_text='只能为10位纯字母', max_length=10, unique=True, validators=[server.constant.validator.SymbolValidator()], verbose_name='场景码')),
                ('scene', models.PositiveSmallIntegerField(choices=[(0, '场景码'), (11, '挪车码'), (22, '行李贴'), (33, '宠物牌')], default=0, verbose_name='场景')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, '初始化'), (10, '已就绪'), (30, '已发行'), (50, '已激活')], default=0, verbose_name='状态')),
                ('qrimg', models.ImageField(default=None, null=True, upload_to=server.third.aliyun.oss.oss_path.publication_qrimg, verbose_name='二维码')),
                ('published_at', models.DateTimeField(db_index=True, default=None, null=True, verbose_name='发行时间')),
                ('activated_at', models.DateTimeField(db_index=True, default=None, null=True, verbose_name='激活时间')),
                ('channel', models.CharField(db_index=True, default='', max_length=50, verbose_name='发行渠道')),
                ('usrid', models.BigIntegerField(db_index=True, default=0, verbose_name='激活绑定用户')),
                ('batch', models.PositiveSmallIntegerField(default=0, verbose_name='发行批次')),
                ('version', models.PositiveSmallIntegerField(default=1, verbose_name='版本')),
                ('subject', models.ForeignKey(db_column='subject_id', db_constraint=False, on_delete=django.db.models.deletion.PROTECT, to='release.subject', verbose_name='主题')),
            ],
            options={
                'verbose_name': 'Publication',
                'verbose_name_plural': 'Publication',
                'db_table': 'k_ls_publication',
                'ordering': ('-pk',),
                'index_together': {('scene', 'batch', 'status')},
            },
        ),
    ]
