# Generated by Django 3.1.2 on 2020-10-26 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('release', '0006_auto_20201025_2359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='coords',
        ),
        migrations.AddField(
            model_name='subject',
            name='position',
            field=models.JSONField(blank=True, default=dict, help_text='SIZE:素材图片尺寸，COORDS:二维码左上角坐标，STATURE:二维码占位大小', verbose_name='素材尺寸及二维码大小和坐标'),
        ),
    ]
