# Generated by Django 3.1.2 on 2020-10-30 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('release', '0007_auto_20201026_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='memo',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='备忘'),
        ),
        migrations.AddField(
            model_name='subject',
            name='spuid',
            field=models.CharField(blank=True, db_index=True, default='', max_length=20, verbose_name='微信小商店SKU'),
        ),
    ]
