# Generated by Django 3.1 on 2020-08-27 06:29

import django.contrib.postgres.fields
import django.contrib.postgres.fields.citext
from django.db import migrations, models
import server.corelib.sequence.instaflake


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='更新时间')),
                ('extra', models.JSONField(default=dict, verbose_name='扩展数据')),
                ('bid', models.BigIntegerField(default=server.corelib.sequence.instaflake.bid_generator, primary_key=True, serialize=False)),
                ('convid', models.UUIDField(unique=True, verbose_name='会话')),
                ('last_id', models.BigIntegerField(db_index=True, default=0, verbose_name='最新消息')),
                ('last_by', models.BigIntegerField(db_index=True, default=0, verbose_name='最新消息发送者')),
                ('last_at', models.DateTimeField(db_index=True, default=None, null=True, verbose_name='最新消息时间')),
                ('symbol', models.CharField(db_index=True, default='', max_length=10, verbose_name='场景码或用户码')),
                ('members', django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(default=0, verbose_name='用户'), db_index=True, size=2, verbose_name='成员')),
                ('called', models.PositiveIntegerField(default=0, verbose_name='通话次数')),
                ('count', models.PositiveIntegerField(default=0, verbose_name='消息总量')),
                ('attrs', models.JSONField(default=dict, verbose_name='自定义属性')),
            ],
            options={
                'verbose_name': 'Conversation',
                'verbose_name_plural': 'Conversation',
                'db_table': 'k_cv_conversation',
                'ordering': ['-last_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportUser',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='更新时间')),
                ('extra', models.JSONField(default=dict, verbose_name='扩展数据')),
                ('touchid', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='用户')),
                ('is_disable', models.BooleanField(default=False, verbose_name='是否禁用')),
                ('disabled_at', models.DateTimeField(default=None, null=True, verbose_name='禁用时间')),
                ('disable_txt', models.TextField(default='', verbose_name='禁用原因')),
                ('active_txt', models.TextField(default='', verbose_name='解除禁用原因')),
                ('count_report', models.PositiveSmallIntegerField(default=0, verbose_name='被举报次数')),
                ('count_user', models.PositiveSmallIntegerField(default=0, verbose_name='被举报用户人数')),
                ('operator', models.PositiveIntegerField(default=0, verbose_name='运营操作员')),
            ],
            options={
                'verbose_name': 'ReportUser',
                'verbose_name_plural': 'ReportUser',
                'db_table': 'k_rt_reportuser',
                'ordering': ('-updated_at',),
                'index_together': {('is_disable', 'operator', 'count_user')},
            },
        ),
        migrations.CreateModel(
            name='ReportRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='更新时间')),
                ('extra', models.JSONField(default=dict, verbose_name='扩展数据')),
                ('usrid', models.BigIntegerField(db_index=True, verbose_name='用户')),
                ('touchid', models.BigIntegerField(db_index=True, verbose_name='对方')),
                ('kind', models.PositiveSmallIntegerField(choices=[(0, '其他'), (120, '垃圾营销'), (130, '恶意骚扰'), (140, '色情低俗'), (150, '欺诈威胁'), (160, '有害违法')], default=0, verbose_name='类型')),
                ('kind_txt', models.CharField(default='', max_length=50, verbose_name='类型描述')),
                ('is_offend', models.BooleanField(default=False, verbose_name='是否反感')),
                ('offended', models.CharField(default='', max_length=200, verbose_name='反感原因或感受')),
                ('evidence', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(default=''), size=5, verbose_name='证据')),
                ('is_solved', models.BooleanField(default=False, verbose_name='是否已解决')),
                ('feedback', models.CharField(default='', max_length=200, verbose_name='给举报者的反馈')),
                ('operator', models.PositiveIntegerField(default=0, verbose_name='运营操作员')),
                ('memo', models.TextField(default='', verbose_name='运营备忘')),
            ],
            options={
                'verbose_name': 'ReportRecord',
                'verbose_name_plural': 'ReportRecord',
                'db_table': 'k_rt_reportrecord',
                'ordering': ('-updated_at',),
                'index_together': {('kind', 'is_offend', 'is_solved')},
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='更新时间')),
                ('extra', models.JSONField(default=dict, verbose_name='扩展数据')),
                ('bid', models.BigIntegerField(default=server.corelib.sequence.instaflake.bid_generator, primary_key=True, serialize=False)),
                ('convid', models.UUIDField(db_index=True, verbose_name='会话')),
                ('sender', models.BigIntegerField(db_index=True, verbose_name='发送者')),
                ('symbol', models.CharField(db_index=True, default='', max_length=10, verbose_name='场景码或用户码')),
                ('status', models.SmallIntegerField(choices=[(0, '初始状态'), (10, '正在发送'), (20, '已发送'), (30, '已送达'), (40, '发送失败')], default=0, verbose_name='状态')),
                ('msg_type', models.SmallIntegerField(choices=[(1, '触发消息'), (2, '留言消息'), (3, '短信提醒'), (5, '双呼通话')], verbose_name='消息类型')),
                ('msg_body', models.JSONField(default=dict, verbose_name='上下文信息')),
                ('reach', models.SmallIntegerField(default=0, verbose_name='通话触达状态')),
                ('content', models.CharField(default='', max_length=255, verbose_name='内容')),
                ('read_at', models.DateTimeField(default=None, null=True, verbose_name='阅读时间')),
                ('is_timed', models.BooleanField(default=False, verbose_name='是否显示时间')),
                ('location', models.JSONField(default=dict, verbose_name='位置信息')),
                ('is_del', models.BooleanField(default=False, verbose_name='标记删除')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Message',
                'db_table': 'k_cv_message',
                'ordering': ('-pk',),
                'index_together': {('msg_type', 'status', 'reach', 'is_del')},
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='更新时间')),
                ('extra', models.JSONField(default=dict, verbose_name='扩展数据')),
                ('bid', models.BigIntegerField(default=server.corelib.sequence.instaflake.bid_generator, primary_key=True, serialize=False)),
                ('convid', models.UUIDField(db_index=True, verbose_name='会话')),
                ('usrid', models.BigIntegerField(db_index=True, verbose_name='用户')),
                ('touchid', models.BigIntegerField(db_index=True, verbose_name='对方')),
                ('phoneid', models.BigIntegerField(db_index=True, verbose_name='手机号(用户)')),
                ('unread', models.PositiveSmallIntegerField(default=0, verbose_name='未读消息量')),
                ('read_at', models.DateTimeField(default=None, null=True, verbose_name='最后阅读')),
                ('is_block', models.BooleanField(default=False, verbose_name='屏蔽对方')),
                ('keywords', django.contrib.postgres.fields.citext.CICharField(db_index=True, default='', max_length=255, verbose_name='检索关键字')),
                ('remark', models.CharField(default='', max_length=50, verbose_name='备注')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contact',
                'db_table': 'k_cv_contact',
                'ordering': ('-updated_at',),
                'unique_together': {('usrid', 'touchid')},
            },
        ),
    ]
