# Generated by Django 3.1.2 on 2020-10-30 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('convert', '0002_remove_contact_phoneid'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='message',
            index_together={('msg_type', 'reach', 'is_del', 'is_timed')},
        ),
        migrations.RemoveField(
            model_name='message',
            name='status',
        ),
    ]
