# Generated by Django 3.1.2 on 2020-11-02 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convert', '0003_auto_20201030_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='receiver',
            field=models.BigIntegerField(db_index=True, default=0, verbose_name='接收者'),
        ),
        migrations.AlterField(
            model_name='message',
            name='msg_type',
            field=models.SmallIntegerField(choices=[(1, '触发消息'), (2, '留言消息'), (5, '双呼通话')], verbose_name='消息类型'),
        ),
    ]
