# Generated by Django 3.1.1 on 2020-09-07 11:53

from django.db import migrations, models
import server.third.aliyun.oss.oss_path


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default=None, null=True, upload_to=server.third.aliyun.oss.oss_path.profile_avatar, verbose_name='头像'),
        ),
    ]
