# Generated by Django 3.1.1 on 2020-09-15 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_usercode_qrimg'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Consignee',
        ),
        migrations.DeleteModel(
            name='DriverLicense',
        ),
    ]
