# Generated by Django 3.1.1 on 2020-09-19 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20200916_0230'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercode',
            name='pages',
            field=models.PositiveIntegerField(default=0, verbose_name='页面量'),
        ),
        migrations.AddField(
            model_name='usercode',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='查询量'),
        ),
    ]
