# Generated by Django 3.1.2 on 2020-10-15 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_userprofile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oauthwechat',
            name='usrid',
            field=models.BigIntegerField(default=None, null=True, unique=True, verbose_name='用户'),
        ),
    ]
