# Generated by Django 3.1.2 on 2020-10-28 09:01

from django.db import migrations, models
import server.corelib.sequence.instaflake


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20201015_1601'),
    ]

    operations = [
        migrations.CreateModel(
            name='OAuthWechatApp',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='更新时间')),
                ('extra', models.JSONField(default=dict, verbose_name='扩展数据')),
                ('bid', models.BigIntegerField(default=server.corelib.sequence.instaflake.bid_generator, primary_key=True, serialize=False)),
                ('openid', models.CharField(db_index=True, default='', max_length=50, verbose_name='应用标识')),
                ('app_type', models.CharField(choices=[('mpa', '小程序')], max_length=20, verbose_name='应用类型')),
                ('unionid', models.CharField(db_index=True, default='', max_length=50, verbose_name='平台唯一标识')),
                ('session_at', models.DateTimeField(default=None, null=True, verbose_name='会话更新时间')),
                ('session_key', models.CharField(default='', max_length=50, verbose_name='会话密钥')),
                ('usrid', models.BigIntegerField(db_index=True, default=0, verbose_name='用户')),
            ],
            options={
                'verbose_name': 'OAuthWechatApp',
                'verbose_name_plural': 'OAuthWechatApp',
                'db_table': 'k_ac_oauth_wechat_app',
                'ordering': ('-pk',),
                'unique_together': {('openid', 'app_type')},
            },
        ),
    ]
