# Generated by Django 3.1 on 2020-08-27 06:29

from django.db import migrations, models
import server.corelib.dealer.deal_time
import server.corelib.sequence.instaflake


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BillDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='更新时间')),
                ('extra', models.JSONField(default=dict, verbose_name='扩展数据')),
                ('usrid', models.BigIntegerField(db_index=True, verbose_name='用户')),
                ('amount', models.IntegerField(default=0, verbose_name='金额')),
                ('balance', models.IntegerField(default=0, verbose_name='余额')),
                ('summary', models.CharField(default='', max_length=120, verbose_name='摘要')),
                ('bill_at', models.DateTimeField(db_index=True, default=server.corelib.dealer.deal_time.get_now, verbose_name='入账时间')),
                ('bill_type', models.SmallIntegerField(choices=[(111, '完成注册'), (121, '实名认证'), (123, '驾驶员认证'), (131, '车辆添加'), (151, '邀请注册'), (152, '被邀请注册'), (21, '微信支付'), (-22, '短息提醒'), (-25, '通话')], verbose_name='交易类型')),
                ('instid', models.BigIntegerField(db_index=True, default=0, verbose_name='关联对象')),
                ('month_id', models.IntegerField(db_index=True, default=0, verbose_name='月度账单')),
                ('is_del', models.BooleanField(default=False, verbose_name='已删除')),
            ],
            options={
                'verbose_name': 'BillDetail',
                'verbose_name_plural': 'BillDetail',
                'db_table': 'k_bl_bill_detail',
                'ordering': ('-bill_at', '-pk'),
            },
        ),
        migrations.CreateModel(
            name='UserBalance',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='更新时间')),
                ('extra', models.JSONField(default=dict, verbose_name='扩展数据')),
                ('usrid', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='用户')),
                ('reward', models.PositiveIntegerField(default=0, verbose_name='活动奖励')),
                ('charge', models.PositiveIntegerField(default=0, verbose_name='累计充值')),
                ('expend', models.PositiveIntegerField(default=0, verbose_name='累计消费')),
                ('last_bill', models.IntegerField(default=0, verbose_name='最新账单')),
                ('amount', models.IntegerField(default=0, verbose_name='余额')),
            ],
            options={
                'verbose_name': 'UserBalance',
                'verbose_name_plural': 'UserBalance',
                'db_table': 'k_bl_user_balance',
            },
        ),
        migrations.CreateModel(
            name='WXPay',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='更新时间')),
                ('extra', models.JSONField(default=dict, verbose_name='扩展数据')),
                ('bid', models.BigIntegerField(default=server.corelib.sequence.instaflake.bid_generator, primary_key=True, serialize=False)),
                ('usrid', models.BigIntegerField(db_index=True, verbose_name='用户')),
                ('amount', models.PositiveIntegerField(default=0, verbose_name='金额')),
                ('body', models.CharField(db_index=True, default='', max_length=50, verbose_name='商品描述')),
                ('openid', models.CharField(db_index=True, default='', max_length=50, verbose_name='微信小程序用户标识')),
                ('trade_no', models.CharField(default=None, max_length=50, null=True, unique=True, verbose_name='商户订单号')),
                ('pay_type', models.PositiveSmallIntegerField(choices=[(1, '充值'), (2, '打印')], default=0, verbose_name='类型')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, '已关闭'), (10, '待支付'), (20, '成功'), (40, '失败')], default=0, verbose_name='状态')),
                ('transaction', models.CharField(db_index=True, default='', max_length=50, verbose_name='微信订单号')),
                ('prepay_id', models.CharField(db_index=True, default='', max_length=50, verbose_name='微信预支付ID')),
                ('trade_at', models.DateTimeField(default=None, null=True, verbose_name='交易成功时间')),
            ],
            options={
                'verbose_name': 'WXPay',
                'verbose_name_plural': 'WXPay',
                'db_table': 'k_bl_wxpay',
            },
        ),
        migrations.CreateModel(
            name='BillMonth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='更新时间')),
                ('extra', models.JSONField(default=dict, verbose_name='扩展数据')),
                ('month', models.DateField(verbose_name='月份')),
                ('usrid', models.BigIntegerField(db_index=True, verbose_name='用户')),
                ('count', models.PositiveIntegerField(default=0, verbose_name='交易量')),
                ('income', models.PositiveIntegerField(default=0, verbose_name='累计充值')),
                ('outlay', models.PositiveIntegerField(default=0, verbose_name='累计消费')),
                ('before', models.IntegerField(default=0, verbose_name='上月结余')),
                ('amount', models.IntegerField(default=0, verbose_name='余额')),
            ],
            options={
                'verbose_name': 'BillMonth',
                'verbose_name_plural': 'BillMonth',
                'db_table': 'k_bl_bill_month',
                'ordering': ('-month', '-pk'),
                'unique_together': {('month', 'usrid')},
            },
        ),
    ]
