# Generated by Django 3.1.2 on 2020-10-12 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserBalance',
        ),
        migrations.RemoveField(
            model_name='billdetail',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='billdetail',
            name='bill_type',
        ),
        migrations.RemoveField(
            model_name='billmonth',
            name='before',
        ),
        migrations.RemoveField(
            model_name='billmonth',
            name='income',
        ),
        migrations.RemoveField(
            model_name='billmonth',
            name='outlay',
        ),
        migrations.AlterField(
            model_name='billdetail',
            name='amount',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='金额'),
        ),
        migrations.AlterField(
            model_name='billdetail',
            name='instid',
            field=models.BigIntegerField(db_index=True, default=0, verbose_name='通话记录'),
        ),
        migrations.AlterField(
            model_name='billmonth',
            name='amount',
            field=models.PositiveIntegerField(default=0, verbose_name='消费金额'),
        ),
        migrations.AlterField(
            model_name='wxpay',
            name='pay_type',
            field=models.PositiveSmallIntegerField(choices=[(1, '充值'), (2, '打印'), (10, '通话')], default=0, verbose_name='类型'),
        ),
    ]
