# Generated by Django 3.1.2 on 2020-10-15 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_auto_20201015_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='billdetail',
            name='is_free',
            field=models.BooleanField(default=False, verbose_name='是否免单'),
        ),
        migrations.AddField(
            model_name='billmonth',
            name='free',
            field=models.PositiveIntegerField(default=0, verbose_name='免单金额'),
        ),
        migrations.AlterField(
            model_name='billdetail',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='是否支付'),
        ),
    ]
